version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
      args:
        MODEL_NAME: ${MODEL_NAME}
    restart: always
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    volumes:
      - ollama_data:/root/.ollama

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: python_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=OllamaChat
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${MODEL_NAME}
    depends_on:
      - db
      - ollama

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        HOST: ${HOST}
    container_name: vue_client
    restart: always
    ports:
      - "80:80"     
    depends_on:
      - server

volumes:
  ollama_data:
  db_data:
